import { Search, SlidersHorizontal } from "lucide-react";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuLabel, DropdownMenuRadioGroup, DropdownMenuRadioItem, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Input } from "@/components/ui/input";
import type { StatusFilter } from "@/module/review/components/ReviewHistoryTypes";

export function ReviewHistoryHeader({ search, onSearchChange, statusFilter, onStatusFilterChange }: { search: string; onSearchChange: (value: string) => void; statusFilter: StatusFilter; onStatusFilterChange: (value: StatusFilter) => void }) {
  return <header className="flex flex-col gap-4 border-b pb-6 lg:flex-row lg:items-end lg:justify-between"><div><h1 className="text-2xl font-semibold tracking-tight">Review History</h1><p className="mt-1.5 text-sm text-muted-foreground">Browse all AI-generated pull request reviews across your repositories.</p></div><div className="flex w-full items-center gap-2 lg:w-auto"><div className="relative min-w-0 flex-1 lg:w-80"><Search className="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={search} onChange={(event) => onSearchChange(event.target.value)} placeholder="Search PR, repo, or review..." className="h-9 pl-9 pr-12" aria-label="Search reviews" /><kbd className="pointer-events-none absolute right-2 top-1/2 -translate-y-1/2 rounded border bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">⌘K</kbd></div><DropdownMenu><DropdownMenuTrigger render={<Button variant="outline" size="default" className="h-9 gap-2" />}><SlidersHorizontal className="size-3.5" /><span className="hidden sm:inline">Filters</span></DropdownMenuTrigger><DropdownMenuContent align="end" className="w-44"><DropdownMenuLabel>Review status</DropdownMenuLabel><DropdownMenuSeparator /><DropdownMenuRadioGroup value={statusFilter} onValueChange={(value) => onStatusFilterChange(value as StatusFilter)}><DropdownMenuRadioItem value="all">All reviews</DropdownMenuRadioItem><DropdownMenuRadioItem value="completed">Completed</DropdownMenuRadioItem><DropdownMenuRadioItem value="processing">Processing</DropdownMenuRadioItem><DropdownMenuRadioItem value="failed">Failed</DropdownMenuRadioItem></DropdownMenuRadioGroup></DropdownMenuContent></DropdownMenu></div></header>;
}
