import { ChevronDown, Clock3, ExternalLink, GitBranchIcon, GitPullRequest, MoreHorizontal } from "lucide-react";
import { formatDistanceToNow } from "date-fns";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { ReviewChat } from "@/module/review/components/ReviewChat";
import { ReviewStatusBadge } from "@/module/review/components/ReviewStatusBadge";
import type { ReviewHistoryReview } from "@/module/review/components/ReviewHistoryTypes";

const getReviewSummary = (review: string) => review.replace(/```[\s\S]*?```/g, "").split("\n").map((line) => line.replace(/^#{1,6}\s+|^[-*]\s+|^\d+\.\s+|[*_`]/g, "").trim()).find(Boolean) || "Review details are available for this pull request.";

export function ReviewTableRow({ review, isExpanded, onExpand }: { review: ReviewHistoryReview; isExpanded: boolean; onExpand: () => void }) {
  return <tr className="border-b transition-colors hover:bg-muted/20 lg:table-row"><td className="block px-4 py-4 lg:table-cell"><div className="flex min-w-0 items-start gap-3"><span className="mt-0.5 flex size-8 shrink-0 items-center justify-center rounded-full bg-primary/10 text-primary"><GitPullRequest className="size-4" /></span><div className="min-w-0"><Link href={review.prUrl} target="_blank" className="block truncate text-sm font-semibold hover:text-primary"><span className="mr-2 text-muted-foreground">#{review.prNumber}</span>{review.prTitle}</Link><p className="mt-1 flex items-center gap-1 truncate text-xs text-muted-foreground"><GitBranchIcon className="size-3" />{review.repository.fullName}</p></div></div></td><td className="block px-4 pb-3 lg:table-cell lg:py-4"><p className="line-clamp-2 text-sm leading-5 text-muted-foreground">{getReviewSummary(review.review)}</p>{!isExpanded && <button type="button" onClick={onExpand} className="mt-1 inline-flex items-center gap-1 text-xs font-medium text-primary hover:underline">Show more<ChevronDown className="size-3" /></button>}</td><td className="block px-4 pb-3 lg:table-cell lg:py-4"><ReviewStatusBadge status={review.status} /></td><td className="block px-4 pb-3 text-sm text-muted-foreground lg:table-cell lg:py-4"><span className="inline-flex items-center gap-1.5"><Clock3 className="size-3.5" />{formatDistanceToNow(new Date(review.createdAt), { addSuffix: true })}</span></td><td className="block px-4 pb-4 lg:table-cell lg:py-4"><div className="flex items-center justify-end gap-1"><ReviewChat reviewId={review.id} /><DropdownMenu><DropdownMenuTrigger render={<Button variant="ghost" size="icon-sm" aria-label={`Actions for PR #${review.prNumber}`} />}><MoreHorizontal className="size-4" /></DropdownMenuTrigger><DropdownMenuContent align="end"><DropdownMenuItem render={<Link href={review.prUrl} target="_blank" />}><ExternalLink />View Pull Request</DropdownMenuItem></DropdownMenuContent></DropdownMenu></div></td></tr>;
}
